server:
  port: 9005

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data1
    username: fatimaba
    password: fb@123456
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update


#spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: fatima
#    password: 123456
#    driver-class-name: oracle.jdbc.OracleDriver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  application:
    name: USER_SERVICE