server:
  port: 9004
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: fatima
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: USER_SERVICE